using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PracticeProblems
{
    class EvenFibonacciNumbers
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:
        //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        public EvenFibonacciNumbers()
        {
            Console.WriteLine("Input the value to sum even Fibonacci numbers up to:");
            string input = Console.ReadLine();
            int max = 0;
            if (int.TryParse(input, out max))
            {
                Console.WriteLine("----------Solution 1:-----------");
                Solution1(max);
            }
            else
            {
                Console.WriteLine("Invalid Input.");
            }
        }

        private void Solution1(int max)//O(n)
        {
            int x = 1;
            int y = 2;
            int sum = 0;

            while (x < max && y < max)
            {
                if (y > x)
                {
                    if (y % 2 == 0)
                    {
                        sum += y;
                    }
                    x += y;
                }
                else
                {
                    if (x % 2 == 0)
                    {
                        sum += x;
                    }
                    y += x;
                }
            }
            Console.WriteLine(sum);
        }
    }
}